apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: server
  name: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: server
    spec:
      volumes:                        
          - name: logging-pv-storage
            persistentVolumeClaim:
              claimName: logging-volume-claim
          - name: log-config
            configMap:
              name: fluentd-config
      containers:
      - name: server
        image: evgenyarbatov/http-server:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
          - mountPath: "/var/log/nginx/"
            name: logging-pv-storage
      - name: fdlogger
        image: fluentd
        env:
          - name: FLUENTD_OPT
            value: -c /etc/fluentd-config/fluent.conf
        volumeMounts:
          - name: logging-pv-storage
            mountPath: "/var/log"
          - name: log-config
            mountPath: "/etc/fluentd-config"
status: {}