apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kube.*
      read_from_head true
      <parse>
        @type json
      </parse>
    </source>

    <filter kube.**>
      @type kubernetes_metadata
    </filter>

    <match kube.**>
      @type elasticsearch
      host elasticsearch-es-http.default.svc
      port 9200
      scheme https
      ssl_verify false
      index_name fluentd
      type_name fluentd
      include_tag_key true
      tag_key @log_name
      logstash_format true
      logstash_prefix kubernetes
      flush_interval 1s
    </match>
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      containers:
      - name: fluentd
        image: fluent/fluentd:v1.16-debian-1
        volumeMounts:
        - name: config-volume
          mountPath: /fluentd/etc
        - name: varlogcontainers
          mountPath: /var/log/containers
      volumes:
      - name: config-volume
        configMap:
          name: fluentd-config
      - name: varlogcontainers
        hostPath:
          path: /var/log/containers
