kind: PersistentVolume
apiVersion: v1
metadata:
  name: logging-volume
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/logs"
